name: Build APK
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install workloads
        run: dotnet workload install maui android
             
      - name: Prepare Resources
        run: |
          mkdir Platforms/Android/Resources/drawable
          mkdir Platforms/Android/Resources/values
          mkdir Platforms/Android/Resources/mipmap-anydpi-v26
          
      - name: Build
        run: dotnet build PakRunner.csproj -c Release -f net8.0-android -p:AndroidManifest=Platforms/Android/AndroidManifest.xml -p:AndroidEnablePreBuildAot=true -p:AndroidSigningKeyPass=pass -p:AndroidSigningStorePass=pass -p:AndroidPackageFormat=apk
               
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/Release/net8.0-android/*-Signed.apk
