name: Build APK
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install workloads
        run: |
          dotnet workload install maui android
          
      - name: Verify resources
        run: |
          ls -R Platforms/Android/Resources/
          
      - name: Build
        run: |
          dotnet build PakRunner.csproj -c Release -f net8.0-android \
            -p:AndroidManifest=Platforms/Android/AndroidManifest.xml \
            -p:AndroidSigningKeyPass=pass \
            -p:AndroidSigningStorePass=pass
            
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/Release/net8.0-android/*-Signed.apk
