name: Verify Files
  run: |
    ls -R Platforms/Android/Resources/
    cat Platforms/Android/Resources/mipmap-anydpi-v26/appicon.xml

name: Build APK
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload install android
          
      - name: Prepare Android resources
        run: |
          mkdir -p Platforms/Android/Resources/{drawable,drawable-v31,values,mipmap-anydpi-v26,mipmap-anydpi-v31}
          
      - name: Build APK
        run: |
          dotnet build PakRunner.csproj -c Release -f net8.0-android -p:AndroidManifest=Platforms/Android/AndroidManifest.xml -p:AndroidPackageFormat=apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pakrunner.apk
          path: bin/Release/net8.0-android/*-Signed.apk
