name: Build APK
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload install android
          
      - name: Build APK
        run: |
          # Create required directories if they don't exist
          mkdir -p Platforms/Android/Resources/{drawable,values,mipmap-anydpi-v26}
          dotnet build PakRunner.csproj -c Release -f net8.0-android -p:AndroidManifest=Platforms/Android/AndroidManifest.xml
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pakrunner.apk
          path: bin/Release/net8.0-android/*-Signed.apk
